[build-system]
requires = ["flit_scm"]
build-backend = "flit_scm:buildapi"

[project]
name = "metupy"
version = "0.2.3"
description = "Metupy is Markdown Engine Template Utilities for Python!"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["markdown", "flask", "documentation", "docs-generator", "metupy"]

authors = [
    { name = "palembangpy", email = "palembangpy@gmail.com" }
]
maintainers = [
    { name = "tomsdroid", email = "tomsdroid007@gmail.com" }
]

dependencies = [
    "click>=8.1.0",
    "flask>=3.0.0",
    "markdown>=3.5.0",
    "requests>=2.31.0",
    "toml>=0.10.2",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Documentation",
    "Topic :: Text Processing :: Markup :: Markdown",
    "Framework :: Flask",
]

[project.urls]
Homepage = "https://metupy.com"
Documentation = "https://docs.metupy.com/"
Repository = "https://github.com/palembangpy/metupy.git"
"Bug Tracker" = "https://github.com/palembangpy/metupy/issues"

[project.scripts]
metupy = "metupy.cli:cli"
