import io
import os
import shutil
import sys
import urllib.request
import zipfile
import click
import markdown
from metupy.engine import MetupyServer

COMPONENTS_INIT_TEMPLATE = '''import os
import sys
import re
import importlib.util

_cache = {}

def _get_active_theme() -> str:
    toml_path = os.path.join(os.getcwd(), "pyproject.toml")
    if os.path.exists(toml_path):
        try:
            try:
                import tomllib
            except ImportError:
                import tomllib as tomllib
            with open(toml_path, "rb") as f:
                data = tomllib.load(f)
                return data.get("tool", {}).get("metupy", {}).get("theme", "default")
        except Exception:
            pass
    return "default"

def __getattr__(name: str):
    if name in _cache:
        return _cache[name]
        
    file_name = re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()
    cwd = os.getcwd()
    active_theme = _get_active_theme()
    
    import metupy
    lib_dir = os.path.dirname(os.path.abspath(metupy.__file__))

    possible_paths = [
        os.path.join(cwd, 'components', f"{file_name}.py"),
        os.path.join(cwd, 'templates', active_theme, 'components', f"{file_name}.py"),
        os.path.join(lib_dir, 'templates', active_theme, 'components', f"{file_name}.py"),
        os.path.join(lib_dir, 'components_blueprint', f"{file_name}.py"),
    ]

    target_path = None
    for path in possible_paths:
        if os.path.exists(path):
            target_path = path
            break

    if not target_path:
        raise AttributeError(f"Component '{name}' (file: {file_name}.py) not found.")

    module_name = f"components._dynamic_{file_name}"
    spec = importlib.util.spec_from_file_location(module_name, target_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Failed to load module for component '{name}'")

    mod = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = mod
    spec.loader.exec_module(mod)

    component_cls = getattr(mod, name, None)
    if not component_cls:
        for attr in dir(mod):
            if not attr.startswith('_') and isinstance(getattr(mod, attr), type):
                component_cls = getattr(mod, attr)
                break

    if not component_cls:
        raise AttributeError(f"Class '{name}' not found in {target_path}")

    _cache[name] = component_cls
    return component_cls
'''


@click.group()
def cli():
    """Metupy CLI - Modern Python SSG Framework."""
    pass


@cli.command()
@click.argument('project_name')
def init(project_name):
    """Initialize a new Metupy project."""
    base_dir = os.path.join(os.getcwd(), project_name)

    if os.path.exists(base_dir):
        click.secho(f"Folder '{project_name}' already exists!", fg='red')
        return

    pages_dir = os.path.join(base_dir, 'pages')
    assets_dir = os.path.join(base_dir, 'assets')
    components_dir = os.path.join(base_dir, 'components')

    os.makedirs(pages_dir)
    os.makedirs(assets_dir)
    os.makedirs(components_dir)

    library_dir = os.path.dirname(os.path.abspath(__file__))

    # 1. Copy default logo if available
    lib_logo_path = os.path.join(library_dir, "assets", "metupy.png")
    if os.path.exists(lib_logo_path):
        shutil.copy(lib_logo_path, os.path.join(assets_dir, "metupy.png"))

    # 2. Generate components/__init__.py with dynamic loader
    with open(
        os.path.join(components_dir, "__init__.py"), "w", encoding="utf-8"
    ) as f:
        f.write(COMPONENTS_INIT_TEMPLATE)

    # 3. Create initial index page
    index_path = os.path.join(pages_dir, 'index.py')
    index_content = '''# Generated by Metupy Engine
from metupy.page import Page
from components import Button, Tabs, Kbd, Modal, Icon

page = Page(title="Home")

# 1. Initialize Icons
icon_badge = Icon("fa-solid fa-rocket", size="sm")
icon_bolt_title = Icon("fa-solid fa-bolt", size="md")
icon_fast = Icon("fa-solid fa-bolt-lightning", size="xl", color="var(--accent)")
icon_palette = Icon("fa-solid fa-palette", size="xl", color="var(--accent)")
icon_responsive = Icon("fa-solid fa-mobile-screen-button", size="xl", color="var(--accent)")

# 2. CTA Button Components
btn_primary = Button(
    text="Get Started", 
    icon="fa-solid fa-rocket", 
    href="#quickstart", 
    height="44px"
)
btn_github = Button(
    text="GitHub Repo", 
    icon="fa-brands fa-github", 
    href="https://github.com", 
    height="44px"
)

# 3. Code Tabs Demo
code_python = """from metupy.page import Page

page = Page(title="Home")
page.title("Hello World!")"""

code_terminal = "pip install metupy\\nmetupy dev"

tabs_demo = Tabs([
    ("Python", code_python),
    ("Terminal", code_terminal)
])

# 4. Kbd & Modal Components
kbd_shortcut = Kbd(["Ctrl", "K"])

modal_demo = Modal(
    id_name="welcome_modal",
    title="Welcome to Metupy!",
    content="The boilerplate home page is successfully loaded! Components like Modal, Tabs, Button, Kbd, and Icon are now cleanly initialized.",
    trigger_text="Open Interactive Modal"
)

# 5. Inject HTML Content into Page Object
page.raw(f"""
<!-- HERO SECTION -->
<div style="text-align: center; padding: 2.5rem 1rem 1.5rem 1rem; max-width: 800px; margin: 0 auto;">
    <span style="display: inline-flex; align-items: center; padding: 4px 14px; background: var(--accent-glow); color: var(--accent); border-radius: 20px; font-size: 0.85rem; font-weight: 600; margin-bottom: 1.25rem;">
        {icon_badge} Metupy Framework v1.0
    </span>
    <h1 style="font-size: 2.5rem; font-weight: 800; line-height: 1.25; margin-bottom: 1rem; letter-spacing: -0.02em;">
        Build Modern & Fast Python Documentation
    </h1>
    <p style="font-size: 1.1rem; color: var(--text-muted); max-width: 620px; margin: 0 auto 2rem auto; line-height: 1.6;">
        Lightweight Python-based framework for creating interactive, precise, and responsive documentation websites instantly.
    </p>
    <div style="display: flex; gap: 0.85rem; justify-content: center; align-items: center; flex-wrap: wrap;">
        {btn_primary}
        {btn_github}
    </div>
</div>

<!-- QUICKSTART & TABS SECTION -->
<div id="quickstart" style="max-width: 800px; margin: 2.5rem auto 1rem auto;">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; flex-wrap: wrap; gap: 8px;">
        <h2 style="border: none; margin: 0; font-size: 1.3rem; font-weight: 700; display: flex; align-items: center;">
            {icon_bolt_title} Quick Start
        </h2>
        <span style="font-size: 0.85rem; color: var(--text-muted);">
            Press {kbd_shortcut} to search
        </span>
    </div>
    {tabs_demo}
</div>

<!-- FEATURE CARDS GRID -->
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(230px, 1fr)); gap: 1.25rem; max-width: 800px; margin: 2.5rem auto;">
    <div style="padding: 1.25rem; background: var(--bg-surface); border: 1px solid var(--border-color); border-radius: 12px;">
        <div style="margin-bottom: 0.5rem;">{icon_fast}</div>
        <h3 style="margin: 0 0 0.5rem 0; font-size: 1.05rem; font-weight: 600;">Blazing Fast</h3>
        <p style="margin: 0; font-size: 0.875rem; color: var(--text-muted); line-height: 1.5;">High performance with zero heavy dependencies, ready directly from Python.</p>
    </div>
    <div style="padding: 1.25rem; background: var(--bg-surface); border: 1px solid var(--border-color); border-radius: 12px;">
        <div style="margin-bottom: 0.5rem;">{icon_palette}</div>
        <h3 style="margin: 0 0 0.5rem 0; font-size: 1.05rem; font-weight: 600;">Modern Components</h3>
        <p style="margin: 0; font-size: 0.875rem; color: var(--text-muted); line-height: 1.5;">Button, Modal, Tabs, Kbd, and Icon components pre-styled for elegance.</p>
    </div>
    <div style="padding: 1.25rem; background: var(--bg-surface); border: 1px solid var(--border-color); border-radius: 12px;">
        <div style="margin-bottom: 0.5rem;">{icon_responsive}</div>
        <h3 style="margin: 0 0 0.5rem 0; font-size: 1.05rem; font-weight: 600;">100% Responsive</h3>
        <p style="margin: 0; font-size: 0.875rem; color: var(--text-muted); line-height: 1.5;">Fully optimized UI layout for desktop and mobile displays.</p>
    </div>
</div>

<!-- INTERACTIVE DEMO BOX -->
<div style="text-align: center; max-width: 800px; margin: 2.5rem auto 1rem auto; padding: 2rem 1.5rem; background: var(--bg-surface); border: 1px solid var(--border-color); border-radius: 14px;">
    <h3 style="margin-top: 0; margin-bottom: 0.5rem; font-size: 1.2rem;">Interactive Feature Demo</h3>
    <p style="color: var(--text-muted); font-size: 0.925rem; margin-bottom: 1.25rem;">Click the button below to trigger an interactive dialog modal powered by Alpine.js.</p>
    {modal_demo}
</div>
""")
'''
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(index_content)

    # 4. Create pyproject.toml configuration file
    toml_path = os.path.join(base_dir, 'pyproject.toml')
    toml_content = f"""[project]
name = "{project_name}"
version = "0.1.0"
description = "Documentation created with Metupy"
requires-python = ">=3.10"
dependencies = ["metupy"]

[tool.metupy]
theme = "default"
use_darkmode = true
use_search = true
logo = "/assets/metupy.png"

[tool.metupy.icons]
cdn_url = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
prefix = "fa-solid "
"""
    with open(toml_path, 'w', encoding='utf-8') as f:
        f.write(toml_content)

    click.secho(
        f"Project '{project_name}' successfully created! Run 'cd {project_name}'"
        " then 'metupy dev'",
        fg='green',
    )


@cli.command()
@click.argument('component_names', nargs=-1, required=True)
def add(component_names):
    """Add component from blueprint to local ./components/ directory."""
    library_dir = os.path.dirname(os.path.abspath(__file__))
    target_dir = os.path.join(os.getcwd(), 'components')

    os.makedirs(target_dir, exist_ok=True)

    for component_name in component_names:
        file_name = component_name.lower()
        target_path = os.path.join(target_dir, f"{file_name}.py")

        if os.path.exists(target_path):
            click.secho(
                f"Component '{component_name}' already exists in"
                f" ./components/{file_name}.py!",
                fg='yellow',
            )
            continue

        blueprint_path = os.path.join(
            library_dir, 'components_blueprint', f"{file_name}.py"
        )

        if not os.path.exists(blueprint_path):
            click.secho(
                f"Component '{component_name}' not found in default blueprints.",
                fg='red',
            )
            continue

        shutil.copy(blueprint_path, target_path)

        click.secho(
            f"Component '{component_name}' successfully added to"
            f" ./components/{file_name}.py!",
            fg='green',
        )


@cli.command(name="make:page")
@click.argument('path')
def make_page(path):
    """Create a single new page."""
    path = path.replace('.py', '')
    target_dir = os.path.join(os.getcwd(), 'pages')
    os.makedirs(target_dir, exist_ok=True)

    file_path = os.path.join(target_dir, f"{path}.py")
    if os.path.exists(file_path):
        click.secho("Page already exists!", fg='red')
        return

    page_name = os.path.basename(path).replace('_', ' ').capitalize()
    template = (
        f'# Generated by Metupy Engine\nfrom metupy.page import Page\n\npage ='
        f' Page(title="{page_name}")\npage.title("{page_name}'
        f' Page")\npage.text("Welcome to {page_name} page")\n'
    )
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(template)

    click.secho(f"Page created: ./pages/{path}.py", fg='green')


@cli.command(name="make:pagegroup")
@click.argument('args', nargs=-1)
def make_pagegroup(args):
    """Create a group of pages (e.g. metupy make:pagegroup docs/setup docs/config)."""
    for arg in args:
        parts = arg.split('/')
        folder = os.path.join(os.getcwd(), 'pages', parts[0])
        os.makedirs(folder, exist_ok=True)

        file_name = f"{parts[1]}.py" if len(parts) > 1 else "index.py"
        file_path = os.path.join(folder, file_name)

        if not os.path.exists(file_path):
            page_name = (
                parts[1].capitalize()
                if len(parts) > 1
                else parts[0].capitalize()
            )
            template = (
                'from metupy.page import Page\n\npage ='
                f' Page(title="{page_name}")\npage.title("{page_name}'
                ' Page")\n'
            )
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(template)
            click.secho(f"Page created: ./pages/{arg}.py", fg='green')


@cli.command(name="make:theme")
@click.argument('theme_name')
def make_theme(theme_name):
    """Create a new custom theme directory in ./templates/."""
    target_dir = os.path.join(os.getcwd(), 'templates', theme_name)

    if os.path.exists(target_dir):
        click.secho(
            f"Theme '{theme_name}' already exists in this project!", fg='red'
        )
        return

    library_dir = os.path.dirname(os.path.abspath(__file__))
    default_theme_dir = os.path.join(library_dir, "templates", "default")

    if not os.path.exists(default_theme_dir):
        click.secho("Default Metupy theme directory not found!", fg='red')
        return

    shutil.copytree(default_theme_dir, target_dir)

    click.secho(
        f"Theme '{theme_name}' successfully created at"
        f" ./templates/{theme_name}/",
        fg='green',
    )
    click.secho(
        f'Activate this theme by setting theme = "{theme_name}" in'
        ' pyproject.toml',
        fg='yellow',
    )


@cli.command(name="install:theme")
@click.argument('repo_path')
def install_theme(repo_path):
    """Download and install a theme from GitHub."""
    repo_clean = repo_path.replace("https://github.com/", "").strip("/")
    parts = repo_clean.split("/")

    if len(parts) < 2:
        click.secho(
            "Invalid repository format! Use 'username/repo-name'", fg='red'
        )
        return

    user, repo = parts[0], parts[1]
    theme_name = repo.replace("metupy-theme-", "").replace("metupy-", "")
    target_dir = os.path.join(os.getcwd(), 'templates', theme_name)

    click.secho(
        f"Downloading theme '{theme_name}' from GitHub ({user}/{repo})...",
        fg='cyan',
    )

    urls_to_try = [
        f"https://github.com/{user}/{repo}/archive/refs/heads/main.zip",
        f"https://github.com/{user}/{repo}/archive/refs/heads/master.zip",
    ]

    zip_bytes = None
    for url in urls_to_try:
        try:
            req = urllib.request.Request(
                url, headers={'User-Agent': 'Mozilla/5.0'}
            )
            with urllib.request.urlopen(req) as response:
                if response.status == 200:
                    zip_bytes = response.read()
                    break
        except Exception:
            continue

    if not zip_bytes:
        click.secho(
            "Failed to download theme repository. Check the GitHub repository"
            " name and branch (main/master).",
            fg='red',
        )
        return

    try:
        with zipfile.ZipFile(io.BytesIO(zip_bytes)) as z:
            root_folder = z.namelist()[0].split('/')[0]

            if os.path.exists(target_dir):
                shutil.rmtree(target_dir)
            os.makedirs(target_dir, exist_ok=True)

            for member in z.infolist():
                if member.filename.startswith(root_folder + "/"):
                    rel_path = member.filename[len(root_folder) + 1 :]
                    if not rel_path:
                        continue

                    dest_path = os.path.join(target_dir, rel_path)
                    if member.is_dir():
                        os.makedirs(dest_path, exist_ok=True)
                    else:
                        os.makedirs(os.path.dirname(dest_path), exist_ok=True)
                        with (
                            z.open(member) as source,
                            open(dest_path, "wb") as target,
                        ):
                            shutil.copyfileobj(source, target)

        click.secho(
            f"Theme '{theme_name}' successfully installed to"
            f" ./templates/{theme_name}/",
            fg='green',
        )
        click.secho(
            f'Set theme = "{theme_name}" in pyproject.toml to use it!',
            fg='yellow',
        )

    except Exception as e:
        click.secho(f"An error occurred while extracting theme: {e}", fg='red')


@cli.command()
@click.option('--port', default=5000)
def dev(port):
    """Run local development server."""
    if os.getcwd() not in sys.path:
        sys.path.insert(0, os.getcwd())

    app = MetupyServer(os.getcwd())
    click.secho(f"Server running at http://localhost:{port}", fg='green')
    app.run(port=port)


@cli.command()
def build():
    """Build static site documentation (HTML & MD)."""
    if os.getcwd() not in sys.path:
        sys.path.insert(0, os.getcwd())

    app = MetupyServer(os.getcwd())
    dist_dir = 'dist'
    sites_dir = os.path.join(dist_dir, 'sites')
    contents_dir = os.path.join(dist_dir, 'contents')
    dist_assets = os.path.join(dist_dir, 'assets')

    if os.path.exists(dist_dir):
        shutil.rmtree(dist_dir)
    os.makedirs(sites_dir, exist_ok=True)
    os.makedirs(contents_dir, exist_ok=True)

    user_assets = os.path.join(os.getcwd(), 'assets')
    if os.path.exists(user_assets):
        shutil.copytree(user_assets, dist_assets)

    theme_name = app.config.get("theme", "default")
    user_theme_dir = os.path.join(os.getcwd(), "templates", theme_name)
    lib_theme_dir = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "templates", theme_name
    )

    if os.path.exists(user_theme_dir):
        active_theme_dir = user_theme_dir
    elif os.path.exists(lib_theme_dir):
        active_theme_dir = lib_theme_dir
    else:
        active_theme_dir = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "templates", "default"
        )

    css_path = os.path.join(active_theme_dir, "style.css")
    default_css = ""
    if os.path.exists(css_path):
        with open(css_path, "r", encoding="utf-8") as f:
            default_css = f.read()

    sidebar_html = "".join([
        f'<a class="menu-link" href="{route}.html">{title}</a>\n'
        for route, title in getattr(app, '_nav_links', [])
    ])
    HTML = (
        '<!DOCTYPE html><html><head><title>{title}</title><style>'
        f'{default_css}'
        '</style></head><body><nav>{sidebar}</nav><main>{content}</main></body></html>'
    )

    for route, page_obj in app._routes.items():
        relative_path = route.strip('/') or 'index'
        os.makedirs(
            os.path.dirname(os.path.join(sites_dir, relative_path)),
            exist_ok=True,
        )
        os.makedirs(
            os.path.dirname(os.path.join(contents_dir, relative_path)),
            exist_ok=True,
        )
        md_content = page_obj.render()
        with open(
            os.path.join(contents_dir, f"{relative_path}.md"),
            'w',
            encoding='utf-8',
        ) as f:
            f.write(md_content)
        html_body = markdown.markdown(
            md_content, extensions=['fenced_code', 'tables']
        )
        with open(
            os.path.join(sites_dir, f"{relative_path}.html"),
            'w',
            encoding='utf-8',
        ) as f:
            f.write(
                HTML.format(
                    title=getattr(page_obj, 'page_title', 'Untitled'),
                    sidebar=sidebar_html,
                    content=html_body,
                )
            )

    click.secho("Static build completed!", fg='green', bold=True)


if __name__ == "__main__":
    cli()
