name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  pypi-publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    
    environment: pypi
    
    permissions:
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set version from Git Tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "Setting pyproject.toml version to: $VERSION"
          sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml

      - name: Clean old build artifacts
        run: rm -rf dist/

      - name: Build Package
        run: uv build

      - name: Publish Package
        run: uv publish
